In [1]:
import pandas as pd
import os
import seaborn as sns
from skbio.diversity import alpha_diversity
from skbio.diversity import beta_diversity
from skbio import TreeNode
from io import StringIO
from skbio.stats.ordination import pcoa

import cx_Oracle

SERVER = 'dboracle.itk.ppke.hu'
PORT = 1521
SERVICE = 'rsc.itk.ppke.hu'
USER = 'metagenome'
PASSWORD = 'LrJPRUS73r84'

class Connection():

    def __init__(self):
        dsn_tns = cx_Oracle.makedsn(SERVER, PORT, service_name=SERVICE)
        self.connection = cx_Oracle.connect(USER, PASSWORD, dsn_tns)

    def get_connection(self):
        return self.connection

    def select(self, sql):
        return pd.read_sql(sql, con=self.connection)

con = Connection()

In [8]:
path = '//gfs/data/curated_metagenomes_metaphlan2/'

files = {}
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for directory in d:
        for r1, d1, f1 in os.walk(os.path.join(path,directory)):
            for file in f1:
                if '.profile.txt' in file:
                    if directory in files:
                        files[directory].append(os.path.join(r1, file))
                    else:
                        files[directory] = [(os.path.join(r1, file))]

In [80]:
def get_data_for_sample(path_to_file):
    dataset = path_to_file.split('/')[-2]
    sample_id = path_to_file.split('/')[-1].split('.')[0]
    
    df = pd.read_csv(path_to_file, delimiter = '\t')
    
    profile_df_2 = df
    profile_df_2['Rank'] = None
    profile_df_2['K'] = None
    profile_df_2['P'] = None
    profile_df_2['C'] = None
    profile_df_2['O'] = None
    profile_df_2['F'] = None
    profile_df_2['G'] = None
    profile_df_2['S'] = None
    profile_df_2['T'] = None
    profile_df_2['Abundance'] = profile_df_2["Metaphlan2_Analysis"]
    
    for p in profile_df_2["#SampleID"]:
        row_level = None
        tags = p.split('|')
        for tag in tags:
            tmp = tag.split('__')
            try:
                level = tmp[0]
                name = tmp[1]
                profile_df_2
                row_level = level

                profile_df_2.loc[profile_df_2['#SampleID'] == p, level] = name
            except: 
                print("Can not split:", tmp)
        profile_df_2.loc[profile_df_2['#SampleID'] == p, 'Rank'] = row_level
    
    def get_name_for_row(row):
        try:
            return row[row.Rank]
        except:
            return '???'
    
    profile_df_2["Name"] = profile_df_2.apply(get_name_for_row, axis=1)

    selected = profile_df_2[["Rank", "Name", "Abundance"]]
    
    selected['Sample_ID'] = sample_id
    selected['Dataset'] = dataset

    
    return selected[["Dataset", "Sample_ID", "Rank", "Name", "Abundance"]]

SyntaxError: invalid syntax (<ipython-input-80-0565991fabc3>, line 38)

In [ ]:
def join_metadata(df, dataset_name):
    SQL_METADATA = """
        select
            DATASET_NAME,
            STUDY_CONDITION,
            BODY_SITE,
            SUBJECTID,
            NCBI_ACCESSION,
            COUNTRY,
            DISEASE,
            GENDER,
            AGE,
            AGE_CATEGORY
        from METADATA
        where dataset_name = '{dataset_name}'
        """.replace("{dataset_name}", dataset_name)
    df_metadata = con.select(SQL_METADATA)
    
    df["DATASET_NAME"] = df["Dataset"]
    merged = df.merge(df_metadata, on='DATASET_NAME')
    
    col_to_idx = {}
    for i in range(len(merged.columns)):
        col_to_idx[merged.columns[i]] = i
    
    joined = merged.loc[[row[1][col_to_idx["Sample_ID"]] in row[1][col_to_idx["NCBI_ACCESSION"]] 
                        for row in merged.iterrows()]]
    
    output = joined[["Sample_ID", "Dataset", "Rank", "Name", "Abundance", 
                     "STUDY_CONDITION", "BODY_SITE", "SUBJECTID",
                     "COUNTRY", "DISEASE", "AGE", "AGE_CATEGORY"]]
    output = output.reset_index()
    output = output.drop(columns="index")
    return output

In [77]:
dataset_dfs = {}
i = 0;
for dataset_name, filelist in files.items():
    if i == 0:
        df_list = []
        for file in filelist:
            print(file)
            df = get_data_for_sample(file)
            if df is not None:
                df_list.append(get_data_for_sample(file))
        df_dataset = pd.concat(df_list)
        output = join_metadata(df_dataset, dataset_name)
        
        path_to_output = os.path.join(path, dataset_name + ".csv")
        with open(path_to_output, "w") as f: 
            f.write(output.to_csv()) 
    i = i+1
    print(dataset_name, " kész.")

//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052021.profile.txt

/gfs/progs/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/gfs/progs/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052022.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052023.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052024.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052025.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052026.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052027.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052028.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052029.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052030.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052031.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052032.profile.txt
Can not split: ['unclassified']
Name is not identifiable.
Can not split: ['unclassified']
Name is not identifiable.
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052033.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052034.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052035.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052036.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052037.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052038.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052039.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052040.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052041.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052042.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052043.profile.txt
//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052044.profile.txt
AsnicarF_2017  kész.
ChngKR_2016  kész.
FengQ_2015  kész.
Heitz-BuschartA_2016  kész.
KarlssonFH_2013  kész.
LeChatelierE_2013  kész.
LiuW_2016  kész.
LomanNJ_2013  kész.
Obregon-TitoAJ_2015  kész.
QinJ_2012  kész.
QinN_2014  kész.
RampelliS_2015  kész.
SchirmerM_2016  kész.
VatanenT_2016  kész.
VogtmannE_2016  kész.
XieH_2016  kész.
YuJ_2015  kész.
ZellerG_2014  kész.

In [34]:
path_to_file = files["AsnicarF_2017"][0]

In [36]:
path_to_file

'//gfs/data/curated_metagenomes_metaphlan2/AsnicarF_2017/SRR4052021.profile.txt'

In [66]:
df = get_data_for_sample(path_to_file)

                       #SampleID  Metaphlan2_Analysis Rank         k  \
0                    k__Bacteria             97.92389    k  Bacteria
1                     k__Viruses              2.07611    k   Viruses
2  k__Bacteria|p__Proteobacteria             78.59277    p  Bacteria
3  k__Bacteria|p__Actinobacteria             12.60032    p  Bacteria
4      k__Bacteria|p__Firmicutes              6.73081    p  Bacteria

                p     c     o     f     g     s     t  Abundance
0            None  None  None  None  None  None  None   97.92389
1            None  None  None  None  None  None  None    2.07611
2  Proteobacteria  None  None  None  None  None  None   78.59277
3  Actinobacteria  None  None  None  None  None  None   12.60032
4      Firmicutes  None  None  None  None  None  None    6.73081

/gfs/progs/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/gfs/progs/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [67]:
df.head()

         Dataset   Sample_ID Rank            Name  Abundance
0  AsnicarF_2017  SRR4052021    k        Bacteria   97.92389
1  AsnicarF_2017  SRR4052021    k         Viruses    2.07611
2  AsnicarF_2017  SRR4052021    p  Proteobacteria   78.59277
3  AsnicarF_2017  SRR4052021    p  Actinobacteria   12.60032
4  AsnicarF_2017  SRR4052021    p      Firmicutes    6.73081

In [68]:
joined = join_metadata(df, "AsnicarF_2017")

In [69]:
joined.head()

,Sample_ID,Dataset,Rank,Name,Abundance,STUDY_CONDITION,BODY_SITE,SUBJECTID,COUNTRY,DISEASE,AGE,AGE_CATEGORY
0,SRR4052021,AsnicarF_2017,k,Bacteria,97.92389,control,stool,MV_FEI1,ITA,healthy,1.0,newborn
1,SRR4052021,AsnicarF_2017,k,Viruses,2.07611,control,stool,MV_FEI1,ITA,healthy,1.0,newborn
2,SRR4052021,AsnicarF_2017,p,Proteobacteria,78.59277,control,stool,MV_FEI1,ITA,healthy,1.0,newborn
3,SRR4052021,AsnicarF_2017,p,Actinobacteria,12.60032,control,stool,MV_FEI1,ITA,healthy,1.0,newborn
4,SRR4052021,AsnicarF_2017,p,Firmicutes,6.73081,control,stool,MV_FEI1,ITA,healthy,1.0,newborn

In [ ]:
profile_df = pd.read_csv(path_to_profile, delimiter = '\t', skiprows = [1])

#f = open("/gfs/data/curated_metagenomes_kraken2/RampelliS_2015⁩/profiled_metagenome.txt", 
#encoding="utf-8")

In [9]:
files.keys()

dict_keys(['AsnicarF_2017', 'ChngKR_2016', 'FengQ_2015', 'Heitz-BuschartA_2016', 'KarlssonFH_2013', 'LeChatelierE_2013', 'LiuW_2016', 'LomanNJ_2013', 'Obregon-TitoAJ_2015', 'QinJ_2012', 'QinN_2014', 'RampelliS_2015', 'SchirmerM_2016', 'VatanenT_2016', 'VogtmannE_2016', 'XieH_2016', 'YuJ_2015', 'ZellerG_2014'])

In [11]:
path_to_file = files["AsnicarF_2017"][0]

In [12]:
dataset = path_to_file.split('/')[-2]
df = pd.read_csv(path_to_file, delimiter = '\t')

In [13]:
df.head()

                       #SampleID  Metaphlan2_Analysis
0                    k__Bacteria             97.92389
1                     k__Viruses              2.07611
2  k__Bacteria|p__Proteobacteria             78.59277
3  k__Bacteria|p__Actinobacteria             12.60032
4      k__Bacteria|p__Firmicutes              6.73081

In [14]:
profile_df_2 = df
profile_df_2['level'] = None
profile_df_2['k'] = None
profile_df_2['p'] = None
profile_df_2['c'] = None
profile_df_2['o'] = None
profile_df_2['f'] = None
profile_df_2['g'] = None
profile_df_2['s'] = None
profile_df_2['t'] = None
profile_df_2['value'] = profile_df_2["Metaphlan2_Analysis"]

In [15]:
profile_df_2.head()

,#SampleID,Metaphlan2_Analysis,level,k,p,c,o,f,g,s,t,value
0,k__Bacteria,97.92389,None,None,None,None,None,None,None,None,None,97.92389
1,k__Viruses,2.07611,None,None,None,None,None,None,None,None,None,2.07611
2,k__Bacteria|p__Proteobacteria,78.59277,None,None,None,None,None,None,None,None,None,78.59277
3,k__Bacteria|p__Actinobacteria,12.60032,None,None,None,None,None,None,None,None,None,12.60032
4,k__Bacteria|p__Firmicutes,6.73081,None,None,None,None,None,None,None,None,None,6.73081

In [16]:
for p in profile_df_2["#SampleID"]:
    row_level = None
    tags = p.split('|')
    for tag in tags:
        tmp = tag.split('__')
        level = tmp[0]
        name = tmp[1]
        profile_df_2
        row_level = level
        
        profile_df_2.loc[profile_df_2['#SampleID'] == p, level] = name
    profile_df_2.loc[profile_df_2['#SampleID'] == p, 'level'] = row_level

In [17]:
profile_df_2.head()

,#SampleID,Metaphlan2_Analysis,level,k,p,c,o,f,g,s,t,value
0,k__Bacteria,97.92389,k,Bacteria,None,None,None,None,None,None,None,97.92389
1,k__Viruses,2.07611,k,Viruses,None,None,None,None,None,None,None,2.07611
2,k__Bacteria|p__Proteobacteria,78.59277,p,Bacteria,Proteobacteria,None,None,None,None,None,None,78.59277
3,k__Bacteria|p__Actinobacteria,12.60032,p,Bacteria,Actinobacteria,None,None,None,None,None,None,12.60032
4,k__Bacteria|p__Firmicutes,6.73081,p,Bacteria,Firmicutes,None,None,None,None,None,None,6.73081

In [22]:
profile_df_2["Name"] = [profile_df_2[i] for i in profile_df_2["level"]]

In [26]:
profile_df_2["Name"]  = profile_df_2.apply(lambda row: row[row.level], axis=1)

In [29]:
selected = profile_df_2[["level", "Name", "value"]]

In [30]:
selected.head()

  level            Name     value
0     k        Bacteria  97.92389
1     k         Viruses   2.07611
2     p  Proteobacteria  78.59277
3     p  Actinobacteria  12.60032
4     p      Firmicutes   6.73081